services:
  web:
    image: ggoneman/bolchaal-web
    ports:
      - 3000:3000
    env_file:
      - ./apps/web/.env
    environment:
      - NEXT_PUBLIC_BASE_URL=https://jinso-clone.sahilahluwalia.com
      - NEXT_PUBLIC_API_URL=https://jinso-clone.sahilahluwalia.com/api
      - NEXT_PUBLIC_WS_URL=wss://jinso-clone.sahilahluwalia.com/ws
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - backend
      - bullmq
    networks:
      - app-network
  backend:
    image: ggoneman/bolchaal-backend
    ports:
      - 3005:3005
      - 3006:3006
    env_file:
      - ./apps/backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/localdb
      - REDIS_URL=redis://:redis123@redis:6379
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - app-network
    depends_on:
      - postgres
      - redis
  bullmq:
    image: ggoneman/bolchaal-bullmq
    env_file:
      - ./apps/bullmq/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/localdb
      - REDIS_URL=redis://:redis123@redis:6379
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - redis
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=localdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=redis123
    command: redis-server --requirepass redis123
    networks:
      - app-network
  caddy:
    image: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - ./caddy_config/Caddyfile:/etc/caddy/Caddyfile:ro,Z
    networks:
      - app-network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/config.json:/config.json:ro
    command:
      - "--label-enable"
      - "--interval"
      - "120"
      - "--rolling-restart"
      - "--cleanup"
      - "--log-level"
      - "fatal"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  caddy_data:

networks:
  app-network:
    driver: bridge 