FROM node:lts-alpine AS builder

# FROM  node:20.11.1-alpine 
ARG DB_URL
# // for tailwind build
# ENV NODE_ENV=development


# RUN apk update \
# 	&& apk add --no-cache openssl libc6-compat openssl3 \
# 	&& rm -rf /var/lib/apt/lists/* \
# 	&& rm -rf /var/cache/apk/*

# RUN echo "=== SYSTEM INFO ===" \
#     && cat /etc/alpine-release \
#     && openssl version \
#     && ls -la /lib/ | grep -E "(libz|libgcc|musl)" \
#     && echo "==================="

RUN corepack enable pnpm
WORKDIR /user/src/app

COPY ./package.json ./pnpm-lock.yaml ./pnpm-workspace.yaml ./
COPY ./turbo.json ./
COPY ./packages/ ./packages/
COPY ./apps/bullmq ./apps/bullmq
# COPY . .

RUN pnpm install --frozen-lockfile
# RUN pnpm turbo build --filter=web

# RUN pnpm run -r build
RUN pnpm run db:generate



RUN pnpm run build --filter=@repo/bullmq

# COPY apps/web/package.json ./package.json

# COPY package.json package.json
# RUN pnpm install

# WORKDIR /

# WORKDIR /
# WORKDIR /user/src/app/apps/bullmq
# COPY ./apps/backend/package.json ./apps/backend/package.json
# // console.log currrent dir
# RUN pnpm run build
# RUN pnpm run build 

EXPOSE 3006

CMD ["pnpm","-w","run","start:bullmq"]
