FROM node:lts-alpine AS builder

# // for tailwind build
# ENV NODE_ENV=development
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_WS_URL
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL

RUN corepack enable pnpm
WORKDIR /user/src/app

COPY ./package.json ./pnpm-lock.yaml ./pnpm-workspace.yaml ./
COPY ./turbo.json ./
COPY ./packages/ ./packages/
COPY ./apps/web ./apps/web
# COPY . .

RUN pnpm install --frozen-lockfile
# RUN pnpm turbo build --filter=web

# WORKDIR /apps/web
# RUN pnpm run -r build
RUN pnpm run build --filter=@repo/web

# COPY apps/web/package.json ./package.json

# COPY package.json package.json
# RUN pnpm install

# WORKDIR /

# WORKDIR /

# // console.log currrent dir
# RUN pnpm run build
# RUN pnpm run build --filter=web

EXPOSE 3000

CMD ["pnpm","run","start:web"]
