#  build docker image
# push to docker hub

name: Build Nextjs Web Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
# // add arg for NEXT_PUBLIC_API_URL in build-push-action
       

      - name: Build Docker Image and Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.web
          tags: |
            ggoneman/bolchaal-web:${{ github.sha }}
            ggoneman/bolchaal-web:latest
          push: true
          build-args: |
            - NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}
            - NEXT_PUBLIC_WS_URL=${{ vars.NEXT_PUBLIC_WS_URL }}
            - NEXT_PUBLIC_BASE_URL=${{ vars.NEXT_PUBLIC_BASE_URL }}
